# init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: mysql-init-container
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: auth-password
        - name: MYSQL_USER
          value: "auth_user"
        - name: MYSQL_HOST
          value: "mysql"  # Set the MySQL Service name or hostname
        - name: MYSQL_PORT
          value: "3306"  # MySQL port, default is 3306
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e

          until mysql -h"${MYSQL_HOST}" -P"${MYSQL_PORT}" -uroot -p"${MYSQL_ROOT_PASSWORD}" -e "SELECT 1" >/dev/null 2>&1; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

          mysql -h"${MYSQL_HOST}" -P"${MYSQL_PORT}" -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOF
          CREATE DATABASE IF NOT EXISTS weatherapp;
          CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_AUTH_PASSWORD}';
          ALTER USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_AUTH_PASSWORD}';
          GRANT ALL PRIVILEGES ON weatherapp.* TO '${MYSQL_USER}'@'%';
          FLUSH PRIVILEGES;
          EOF
      restartPolicy: Never